# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-19 08:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('cost', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_name', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('city', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='cost',
            name='u_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TutionFee.Information'),
        ),
    ]
