# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-26 06:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TutionFee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cost',
            name='cost',
            field=models.IntegerField(max_length=80),
        ),
    ]
