# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-31 13:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_album_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='like',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 7, 31, 13, 38, 4, 146764, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
